# Generated by Django 4.1.1 on 2023-01-30 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_limit', models.DecimalField(decimal_places=5, max_digits=10)),
                ('upper_limit', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Apparatuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_allowed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.allowedvalues')),
                ('id_apparatus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.apparatuses')),
            ],
        ),
        migrations.CreateModel(
            name='Statuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=5, max_digits=10)),
                ('id_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.parameters')),
                ('id_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sensors')),
            ],
        ),
        migrations.AddField(
            model_name='apparatuses',
            name='id_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.statuses'),
        ),
        migrations.AddField(
            model_name='allowedvalues',
            name='id_parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.parameters'),
        ),
    ]
