# Generated by Django 4.1.1 on 2023-02-01 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_sensors_id_allowed_allowedvalues_id_sensor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllowedValues',
            new_name='AllowedValue',
        ),
        migrations.RenameModel(
            old_name='Apparatuses',
            new_name='Apparatus',
        ),
        migrations.RenameModel(
            old_name='Parameters',
            new_name='Parameter',
        ),
        migrations.RenameModel(
            old_name='Sensors',
            new_name='Sensor',
        ),
        migrations.RenameModel(
            old_name='Statuses',
            new_name='Status',
        ),
        migrations.RenameModel(
            old_name='Values',
            new_name='Value',
        ),
    ]
