# Generated by Django 4.1.1 on 2023-02-02 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_allowedvalues_allowedvalue_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allowedvalue',
            old_name='id_parameter',
            new_name='parameter',
        ),
        migrations.RenameField(
            model_name='apparatus',
            old_name='id_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='id_apparatus',
            new_name='apparatus',
        ),
        migrations.RenameField(
            model_name='value',
            old_name='id_parameter',
            new_name='parameter',
        ),
        migrations.RenameField(
            model_name='value',
            old_name='id_sensor',
            new_name='sensor',
        ),
    ]
