# Generated by Django 4.1.1 on 2023-02-04 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_id_parameter_allowedvalue_parameter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApparatusName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apparatus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.apparatus')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower', models.DecimalField(decimal_places=5, max_digits=10)),
                ('upper', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SensorName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Value',
            new_name='Reading',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='apparatus',
        ),
        migrations.AddField(
            model_name='sensor',
            name='parameter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='main.parameter'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AllowedValue',
        ),
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.devicename'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='range',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='main.range'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apparatus',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.apparatusname'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.sensorname'),
        ),
    ]
