# Generated by Django 4.1.1 on 2023-02-04 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_apparatusname_device_devicename_range_sensorname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='parameter',
        ),
        migrations.AddField(
            model_name='reading',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Device_Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.device')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.sensor')),
            ],
        ),
    ]
