# Generated by Django 4.1.1 on 2023-02-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_reading_id_device_sensor_remove_sensor_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='abbreviation',
            field=models.CharField(default='OK', max_length=10),
            preserve_default=False,
        ),
    ]
