# Generated by Django 4.1.7 on 2023-02-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_status_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='time',
            field=models.DateField(auto_now=True),
        ),
    ]
