# Generated by Django 4.1.7 on 2023-02-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_sensor_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
